#!/bin/sh

echo "[rc3.d] rkf-svc RC3 script"
echo "Remote key framework start"
	
if [ -x /usr/bin/rkf_server ]; then
	/usr/bin/rkf_server & 
fi

#if [ -f /opt/etc/.hib_capturing ]; then
##add waitting for widget-screen, request from booting-TF (for Normal Boot) )
#	echo "Fast boot"
#	else
#	echo "waitting for widget-screen about 17s"
#fi
#
